language: cpp
compiler: gcc
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install -qq autoconf libgtk2.0-dev libdbus-glib-1-dev libtag1-dev libgstreamer-plugins-base0.10-dev zip unzip"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:
 - "echo 'ac_add_options --with-taglib-source=packaged' >> nightingale.config"
 - "echo 'ac_add_options --enable-tests' >> nightingale.config"
script: "./build.sh && compiled/dist/nightingale --test"
branches:
  only:
    - sb-trunk-oldxul
notifications:
  irc: "irc.mozilla.org#nightingale"
